services:
  - type: web
    name: flux-downloader
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: YTDLP_NO_UPDATE
        value: True